#############################################################################
# Makefile for building: libRavrProg.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.3) on: Wed May 1 15:33:43 2013
# Project:  RavrProg.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile RavrProg.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wextra -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -D_REENTRANT -Wextra -W -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iqextserialport -I.
LINK          = g++
LFLAGS        = -m64 -shared -Wl,-soname,libRavrProg.so.1
LIBS          = $(SUBLIBS)  -L./qextserialport -L/usr/lib/x86_64-linux-gnu -lqextserialport -lusb -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = RavrProg.cpp \
		U2S.cpp \
		STK500.cpp \
		STK600.cpp \
		AVRDragon.cpp \
		JTAGICEmkI.cpp \
		JTAGICEmkII.cpp \
		USBasp.cpp \
		LUFACDC.cpp \
		Device.cpp 
OBJECTS       = RavrProg.o \
		U2S.o \
		STK500.o \
		STK600.o \
		AVRDragon.o \
		JTAGICEmkI.o \
		JTAGICEmkII.o \
		USBasp.o \
		LUFACDC.o \
		Device.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RavrProg.pro
QMAKE_TARGET  = RavrProg
DESTDIR       = 
TARGET        = libRavrProg.so.1.0.0
TARGETA       = libRavrProg.a
TARGETD       = libRavrProg.so.1.0.0
TARGET0       = libRavrProg.so
TARGET1       = libRavrProg.so.1
TARGET2       = libRavrProg.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	{ test -z "$(DESTDIR)" || cd "$(DESTDIR)"; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index ." -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: RavrProg.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile RavrProg.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile RavrProg.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RavrProg1.0.0 || $(MKDIR) .tmp/RavrProg1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RavrProg1.0.0/ && $(COPY_FILE) --parents RavrProg.h U2S.h STK500.h STK600.h AVRDragon.h JTAGICEmkI.h JTAGICEmkII.h USBasp.h LUFACDC.h Device.h .tmp/RavrProg1.0.0/ && $(COPY_FILE) --parents RavrProg.cpp U2S.cpp STK500.cpp STK600.cpp AVRDragon.cpp JTAGICEmkI.cpp JTAGICEmkII.cpp USBasp.cpp LUFACDC.cpp Device.cpp .tmp/RavrProg1.0.0/ && (cd `dirname .tmp/RavrProg1.0.0` && $(TAR) RavrProg1.0.0.tar RavrProg1.0.0 && $(COMPRESS) RavrProg1.0.0.tar) && $(MOVE) `dirname .tmp/RavrProg1.0.0`/RavrProg1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RavrProg1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

RavrProg.o: RavrProg.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h \
		../Rtk/RConfig.h \
		../Rtk/RFile.h \
		../Rtk/RString.h \
		../Rtk/RTreeNode.h \
		../Rtk/RCom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RavrProg.o RavrProg.cpp

U2S.o: U2S.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o U2S.o U2S.cpp

STK500.o: STK500.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h \
		../Rtk/RConfig.h \
		../Rtk/RFile.h \
		../Rtk/RString.h \
		../Rtk/RTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STK500.o STK500.cpp

STK600.o: STK600.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STK600.o STK600.cpp

AVRDragon.o: AVRDragon.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AVRDragon.o AVRDragon.cpp

JTAGICEmkI.o: JTAGICEmkI.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h \
		../Rtk/RConfig.h \
		../Rtk/RFile.h \
		../Rtk/RString.h \
		../Rtk/RTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JTAGICEmkI.o JTAGICEmkI.cpp

JTAGICEmkII.o: JTAGICEmkII.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h \
		../Rtk/RConfig.h \
		../Rtk/RFile.h \
		../Rtk/RString.h \
		../Rtk/RTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JTAGICEmkII.o JTAGICEmkII.cpp

USBasp.o: USBasp.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o USBasp.o USBasp.cpp

LUFACDC.o: LUFACDC.cpp RavrProg.h \
		../Rtk/rtypes.h \
		../Rtk/RHexFile.h \
		Device.h \
		STK500.h \
		command.h \
		JTAGICEmkI.h \
		JTAGICEmkII.h \
		AVRDragon.h \
		STK600.h \
		U2S.h \
		USBasp.h \
		LUFACDC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LUFACDC.o LUFACDC.cpp

Device.o: Device.cpp ../Rtk/rtypes.h \
		Device.h \
		../Rtk/RConfig.h \
		../Rtk/RFile.h \
		../Rtk/RString.h \
		../Rtk/RTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Device.o Device.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

